### ISSUE TITLE
Default für local-dir

### ISSUE THREAD

**Issue by raphiz** [openhsr/connect#14]
Ich denken, ein Attribut `default-local-dir` wäre nötig - derzeit muss  man für jeden Ordner, den man synchronisiert das attribut `local-dir` (oder so) angeben.
Ich fände dabei eine Variable nett - bsp: `default-local-dir: /home/user/HSR/<name>/skripte`

**Comment by Excape** [comment]
Sollte der `local-dir`, der auf den einzelnen Repositories definiert wird, den `default-local-dir` überschreiben? D.h man definiert  `default-local-dir` und auf den einzelnen repos ist dann `local-dir` optional (und hat Priorität)

**Comment by raphiz** [comment]
@Excape genau! 
Also von mir aus einfach ein Default (auf ebene sync) - und dann wie gehabt die `local-dir`, welche den default überschreiben.

**Comment by Excape** [comment]
Implementiert mit 39264b02b7f801728ced96c45a22d9dcc6448b11
