### ISSUE TITLE
Unterstützung für 32 Bit?

### ISSUE THREAD

**Issue by fabianhauser** [openhsr/connect#18]
Momentan unterstützen wir für Releases nur 64-Bit-Systeme. Das erstellen von 32-Bit Docker Containern ist eher kompliziert (benötigt multiarch-installation, siehe auch #8 ).

Dies ist in erster Linie den `C`-Libraries von PyYAML zu verdanken (der Connect selber hat keine Binaries). PyYAML werden wir vermutlich aufgrund fehlender guter Alternativen in nächster Zeit nicht einfach los.

Die Frage ist, brauchen wir überhaupt 32 Bit Support? Eigentlich gibt es keinen Grund mehr, 32 Bit zu nutzen.

**Comment by raphiz** [comment]
Zur Vollständigkeit: Derzeit haben wir [pureyaml](https://github.com/bionikspoon/pureyaml) als "drop-in-replacement"  für PyYAML getestet - aber der Parser fliegt bei einigen Konfigurationen auf die Schnauze (bsp. bei @murieletrentini )

**Comment by raphiz** [comment]
Zum 32 Bit Support: Ich sehe derzeit kein Grund dafür, 32 Bit zu supporten. Mir fällt schlicht kein überzeugendes Argument ein, Ein 32 Bit System für das Arbeiten an der HSR zu verwenden :thinking:
