### ISSUE TITLE
Festlegung einer Lizenz

### ISSUE THREAD

**Issue by raphiz** [openhsr/connect#2]
Wir müssen uns auf eine Lizenz einigen - vorallem müssen wir auch die Lizenzen unserer Abhägigkeiten im Blick behalten...
Ich persönlich mag die [MIT-Lizenz](https://opensource.org/licenses/MIT)...was meint Ihr?

**Comment by fabianhauser** [comment]
Also ich persönlich bevorzuge die GPL; die hat den Vorteil, das Abwandlungen auch unter der GPL (oder kompatibler Lizenz) sein müssen.

**Comment by raphiz** [comment]
Jup, nach Absprache mit Fabian bin ich auch der Meinung, dass die GPL zumindest für dieses Projekt besser geeignet ist.
