### ISSUE TITLE
Neuer Server

### ISSUE THREAD

**Issue by The-Compiler** [openhsr/connect#26]
Die HSR scheint die Skripte von `\\c206.hsr.ch\skripte` auf `\\svm-c213.hsr.ch\skripte` umzulagern laut [Blog-Eintrag](https://blog.hsr.ch/HSR-Blog/) (nur aus HSR-Netz erreichbar). Ab 30.7. soll dann der alte Pfad nicht mehr gehen.

connect hat c206 momentan hardcoded - ev. sollten wir besser gleich `\\hsr.ch\root\alg\skripte` benutzen falls das geht?

**Comment by fabianhauser** [comment]
Der direkte Zugriff funktioniert leider nicht, da pysmb [DFS nicht unterstützt](https://github.com/miketeo/pysmb/issues/72#issuecomment-256541132). Am besten wäre wohl eine neue Einstellung in der Sync-Konfiguration für den Server?

Grundsätzlich finde ich es aber nicht soo schlecht, wenn die HSR-Share-Hostnamen fix im Code hinterlegt werden, dann können wir diese über ein Connect-update überall in einem Rutsch austauschen...

**Comment by The-Compiler** [comment]
Ja, ich denk auch dass wir das schon hardcoden sollten. Wir muessen es halt jetzt einfach rechtzeitig umstellen :wink:
