### ISSUE TITLE
Synchronisation Dateien

### ISSUE THREAD

**Issue by fabianhauser** [openhsr/connect#4]
- Prüfen ob Änderungen an Remote mittels Änderungsdatum und Size aus JSON
- Prüfen ob lokale Änderungen mittels lokalem Hash aus JSON
- Konfliktbehandlung à la Dropbox

**Comment by Excape** [comment]
sync.py ist erstellt und ins cli implementiert

TODO: Tests schreiben

**Comment by murieletrentini** [comment]
wenn man mitten im Semester erst auf openhsrconnect stösst und zum ersten mal synct, werden alle bisherigen dateien überschrieben. Wäre es nicht schön, wenn er beim syncen prüft, ob noch kein cache-file vorhanden ist und eins anlegt für bereits vorhandene dateien (o.ä.)?

**Comment by fabianhauser** [comment]
Evtl. könnten wir eine Warnmeldung anzeigen? Den Cache direkt anzulegen dürfte ziemlich schwierig sein (z.B. lässt sich nicht erkennen, ob die Datei lokal verändert wurde oder doch nur auf dem Share aktualisiert)...

**Comment by murieletrentini** [comment]
hmm stimmt soweit hab ich nicht überlegt. Warnhinweis ist schonmal etwas.

**Comment by Excape** [comment]
Es wäre kein Problem, den Cache anzulegen für Dateien, die schon im Zielordner sind. Wenn sich dann auf dem Share etwas verändert, wird so vorgegangen wie bei `conflict-handling` konfiguriert... Ausser ich bedenke etwas gerade nicht...
Ich probiere es mal aus :wink:
