### ISSUE TITLE
Storing Secrets / Passwörter Ablegen

### ISSUE THREAD

**Issue by fabianhauser** [openhsr/connect#7]
Die Passwörter sollen auf eine sichere Art abgelegt werden. Siehe auch Diskussion in #1

**Comment by michiwieland** [comment]
# Notizen

# Problemstellung
- Wie sollen die User Passwörter abgelegt werden
- Wie kann CUPS auf die Passwörter zugreifen
- SAMBA macht dies bereits irgendwie. Wie!?
- Python Keyring

# Hinweise
- Keyring lässt nur Applikationen zugreifen, die vom aktuellen Nutzer gestartet wurden
- Als Masterpasswort wird standardmässig das User Passwort verwendet

# Keyring 9.3.1 (latest version)
- MIT License
- Unterstützt MAC OSX Keychain, Freedesktop Secret Service, KWallet, Windows Credintial Valut (alles weitere unter keyrings.alt Paket)

## Vorbereitungen
- https://stackoverflow.com/questions/22073516/failed-to-install-python-cryptography-package-with-pip-and-setup-py
- sudo dnf install python3-devel libffi-devel openssl-devel
- brew install pkg-config libffi openssl
	env LDFLAGS="-L$(brew --prefix openssl)/lib" CFLAGS="-I$(brew --prefix openssl)/include" pip install cryptography)
- sudo dnf install redhat-rpm-config (Ansonsten wird der GCC nicht gefunden)
- sudo pip3 install keyring

## Nutzung
import keyring
keyring.set_password('My namespace', username, password)
keyring.get_password('My namespace', username)
