### ISSUE TITLE
Packaging Linux / Release Prozess

### ISSUE THREAD

**Issue by fabianhauser** [openhsr/connect#8]
Script für einen neuen Release
- `fpm`
- Signing / Private Key
- Repositories
# Vorgehen
- [Mac OS X hombrew package building](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Python-for-Formula-Authors.md) ([brew-pkg required?](https://github.com/timsutton/brew-pkg))
- [Zalando fpm / fpm-cookiery package build for deb/rpm](https://github.com/zalando/package-build)
## Tasklist
- [x] Build-Struktur und Skripte erstellen
- [x] Paketerstellung für Ubuntu Xenial
- [x] `x86_64` support
- [x] Drucker bei installation einrichten
- [x] i386 support
- [x] Auslagern OS X Support in eigenes Issue
- [x] DEB-Repository & GPG-Signierung erstellen
- [x] RPM-Repository mit Signierung erstellen
- [x] Paketerstellung für andere Fedora & Ubuntu Distributionen
- [x] Verzeichnisstruktur für Package-Repositories überarbeiten  (multi distro/release geht nicht so leicht wie ich zuerst dachte)
- [x] Bereinigen scripts
- [x] Neuer PGP-Key (oder neue ID auf bestehendem? Sollte gehen.)
- [x] jemand zweites sollte nach den Schritten oben alle kritischen Teile prüfen, insbesondere:
  - [x] Sicherheit PGP-Key & Signaturen
  - [x] Post-Install und Pre-Remove Scripts
- [ ] `make install` für manuelle Installation implementieren
- [x] Paketierung und Release mit `git tag` und GitHub-Releases via Makefile ermöglichen.
- [x] Continuous Delivery mit Travis

**Comment by fabianhauser** [comment]
In weiten Teilen funktioniert das erstellen von rpm und deb Paketen mit Docker & distributionsspezifischen Abhängigkeiten, siehe [Makefile](https://github.com/openhsr/connect/blob/packaging/Makefile).

Allerdings ist die Komplexität (Package-Format, Distro, Distro-Version, Arch) IMHO  zu hoch für ```make```. Das wird noch durch diverse Spezialfälle erschwert, die FPM nicht selber abhandeln kann
(z.B. Fedora 23: ```easy_install-3.4```, Fedora 24: ```easy_install-3.5```, Ubuntu 16.04: ```easy_install3```).

Ich würde daher vorschlagen, auch das Builden in einem Python-Script zu erledigen.

@raphiz: Einwände / Vorschläge / Tipps?

**Comment by fabianhauser** [comment]
http://www.pyinvoke.org/

**Comment by fabianhauser** [comment]
Kurzes Update zum Packaging-Prozess: Die deb-Builds für Ubuntu Xenial funktionieren grundsätzlich.

Bevor die Repositories von jemandem produktiv eingesetzt werden, muss folgendes noch gemacht werden:
- [ ] Verzeichnisstruktur für Package-Repositories überarbeiten  (multi distro/release geht nicht so leicht wie ich zuerst dachte)
- [ ] Bereinigen scripts
- [ ] Neuer PGP-Key (oder neue ID auf bestehendem? Sollte gehen.)
- [ ] jemand zweites sollte nach den Schritten oben alle kritischen Teile prüfen, insbesondere:
  - [ ] Sicherheit PGP-Key & Signaturen
  - [ ] Post-Install und Pre-Remove Scripts

**Comment by raphiz** [comment]
@fabianhauser Danke viel Mal :tada:
Ich kann mir gerne die Post-Install und Pre-Remove scripts anschauen - für PGP-Keys & Signaturen bin ich nicht der Richtige :wink:

**Comment by raphiz** [comment]
1. ich mache mir etwas sorgen, dass wenn wir für jede distr die preinstall und preuninstall scripts warten müssen...wäre es nicht möglich, da etwas zentraler zu kombinieren? Wir haben ja derzeit eigentlich "nur" den Drucker einzurichten und den Symlink zu setzen - aber was wenn sich das ändert? Müssen dann alle Skripts für alle distros separat angepasst werden?
2. Eine Trennung von docker-related und puren skripts wäre der Übersicht evtl dienlich?
3. Dockerfile wird typischerweise gross geschrieben.
4. Die gpg.conf ist sehr ausführlich kommentiert - diverse elemnte wie Proxy usw. würde ich gerne rausschmeissen, damit nur das relevante drinn ist.

@fabianhauser am besten wir sitzen mal kurz zusammen, ich habe noch ein paar Fragen :wink:

**Comment by raphiz** [comment]
@fabianhauser du musst ja pyyaml gar nicht packen! Gibt es schon seit mind. `precise` in den [Ubuntu Repos](http://packages.ubuntu.com/de/precise/python3-yaml) bzw. auch bei [Debian](https://packages.debian.org/de/sid/python3-yaml)

**Comment by fabianhauser** [comment]
@raphiz oh, das hatte ich nicht gesehen. Danke! :smile:

**Comment by fabianhauser** [comment]
@raphiz ich glaube, wir können dieses Issue schliessen, oder? :)

**Comment by raphiz** [comment]
@fabianhauser Ein Bier um zu feiern fehlt noch  👍 🎉 🎈 🍺 🍻 💪

**Comment by mattbaumann** [comment]
Habt ihr die Packages schon online gestellt? Wenn ja, wo?
Gruess @mattbaumann

**Comment by raphiz** [comment]
@mattbaumann Derzeit [in der README des Packaging](https://github.com/openhsr/connect/blob/master/packaging/README.md)
