### ISSUE TITLE
OpenHSR Connect 2.0

### ISSUE THREAD

**Issue by bytinbit** [openhsr/connect#93]
Hallöchen,

wie manche von euch vielleicht schon wissen, haben wir (@ThunderKey, @The-Compiler, ich) dieses Semester im Rahmen des EPJ eine zweite Version von OpenHSR Connect entwickelt, "kitovu", mit dem Ziel, mehr als "nur" den Skripteserver zu synchronisieren. Und: wir haben es tatsächlich geschafft, Moodle ein Schnippchen zu schlagen, die Synchronisation läuft also mit Skripteserver und Moodle! Falls ihr unsere Präsentation dazu ansehen möchtet, wir halten sie nächste Woche am 30.5. von 11:05-11:30 Uhr. Der Raum steht noch nicht fest, wir halten euch auf dem Laufenden.

Wir kontaktieren euch hier via ein Issue, damit es sicher die richtigen Leute erreicht.

liebe Grüsse,
Méline

**Comment by raphiz** [comment]
Wohoo, danke für die Info! Ich bin sehr gespannt und komme sicher vorbei. Dann können wir uns auch gerne über die Zukunft der beiden Projekte unterhalten :+1:

**Comment by fabianhauser** [comment]
Cool, komme auch gerne an die Präsentation!

Nächsten Dienstag wäre noch die [open\HSR GV](https://github.com/openhsr/verein/pull/31) (ich weiss, etwas kurzfristig...). Falls jemand von euch da ist und lust hat, könnt ihr kitovu gerne auch kurz vorstellen 😃

**Comment by The-Compiler** [comment]
@fabianhauser Das sollte hoffentlich klappen mit der GV - wir haben am Freitag dann halt noch die EPJ-Endabgabe, aber wir gucken, dass wir das hinkriegen.

Wie sieht das denn zeitlich aus? Falls ihr 25 Minuten Zeit (und die Leute die Geduld :laughing:) dafür habt, wär das für uns grad noch ne ideale Hauptprobe für den Vortrag - aber sonst können wir den natürlich auch kürzen.

@ThunderKey ist kein OpenHSR-Mitglied - darf er dann trotzdem an die GV und ggf. ans Pizzafest? Zumindest [die Statuten](https://raw.githubusercontent.com/openhsr/verein/master/statuten/statuten.pdf) scheinen da nix dagegen zu haben.

**Comment by fabianhauser** [comment]
@The-Compiler also von mir aus könnt ihr gerne die Hauptprobe für euren Vortrag machen, allerdings muss das @InverseIntegral absegnen, er leitet die GV.

Und natürlich ist @ThunderKey ebenfalls willkommen (du darfst auch gerne dem Verein beitreten wenn du magst 😉)

**Comment by InverseIntegral** [comment]
Ist meiner Meinung nach in Ordnung!

**Comment by bytinbit** [comment]
Falls trotzdem jemand am Mittwoch an die EPJ-Präsentation kommen mag, dafür haben wir nun auch alle Infos beisammen:

Mittwoch 30. Mai 2018, Raum 1.221, 11:05-11:30 Uhr

Wir freuen uns auf euch! Und natürlich, dass wir das Projekt an der GV präsentieren können :)
